### ISSUE TITLE
CORS question

### ISSUE THREAD

**Issue by AlexCro** [Complexible/stardog.js#42]
Hi all.
How to work correctly with CORS?
```javascript
var conn = new stardog.Connection();

conn.setEndpoint("http://localhost:5820/");
conn.setCredentials("anonymous", "anonymous");

conn.query({
        database: "test",
        query: "select ?s { ?s ?p ?o }"
    },
    function (data) {
        console.log(data.results.bindings);
});
```
This code not work for me.
I'm use browserify and stardog server at localhost:5820.

**Comment by edgarRd** [comment]
You shouldn't need browserify to use stardog, it works directly in the browser. I just added an example in https://github.com/Complexible/stardog.js/tree/develop/examples/browser-app on how to use it.

CORS is supported in stardog. If you're using version < 2.1.2, as mentioned in the README, you may need to run a proxy like the one provided in https://github.com/Complexible/stardog.js/blob/develop/scripts/runCORS.js

**Comment by AlexCro** [comment]
Hi.

**Comment by AlexCro** [comment]
Hi. I found problem. I have project on node.js. I'am use browserify to run app in browser.
When I try to integrate stardog.js to my project, and run browserify, i get CORS error in browser.

In my app.js in browser this code returned 'true'!:
```javascript
var isNode = (typeof exports !== "undefined" && typeof module !== "undefined" && module.exports);
```
If set isNode to true, this worked for me. Is there no other way to check isNode? Sorry for my bad english.
